### ISSUE TITLE
Annotation cache

### ISSUE THREAD

**Issue by bghveding** [ray-di/Ray.Aop#45]
Hi,

I was wondering what your thoughts are regarding the hardcoded AnnotationReader in Bind.php. Would you guys be open to have a reader as a possible constructor argument for example?

In my case I would like to use the CachedReader instead for performance.

PS: Great library!

**Comment by koriym** [comment]
Hello @bghveding

Instead, You can cache `Bind` in your user code. It saves whole binding  process include annotation reading. I add demo code for this at https://github.com/ray-di/Ray.Aop/pull/46

I remove all cache mechanism from `Ray.Aop` and `Ray.Di` component for `v2` aim to have more cleaner design. I intentionally hard code for that constructor, but if you think I'm still missing something, Let me know. Discussion are welcome. :)

> PS: Great library!

Thanks !

**Comment by bghveding** [comment]
Thanks @koriym, that solves it :)

**Comment by koriym** [comment]
@bghveding welcome ! thanks for the feedback. :)
